drop table if exists functionTable;
create table functionTable (name text, condition text, result bit varying);
insert into functionTable values ('level', 'x numeric, y numeric');
insert into functionTable values ('level', 'x=y or ((0<=x and x<2) and (0<=y and y<2))', '11');
insert into functionTable values ('level', '2<=x and x<5 and 2<=y and y<5 and x!=y', '10');
insert into functionTable values ('level', '0<=x and x<2 and 2<=y and y<5', '01');
insert into functionTable values ('level', '2<=x and x<5 and 0<=y and y<2', '01');
insert into functionTable values ('level', '', '00');
insert into functionTable values ('gender', 'x char(1), y char(1)');
insert into functionTable values ('gender', 'x=y', '1');
insert into functionTable values ('gender', 'x!=y', '0');
insert into functionTable values ('size', 'x int, y int');
insert into functionTable values ('size', '(x=y and x is not null and y is not null) or ((70<=x and x<=80) and (70<=y and y<=80))', '11');
insert into functionTable values ('size', 'x is null and y is not null', '10');
insert into functionTable values ('size', 'x is not null and y is null', '10');
insert into functionTable values ('size', '', '01');
